### ISSUE TITLE
error compiling GenerateTrainingSet

### ISSUE THREAD

**Issue by zgojcic** [CVLAB-Unibo/Keypoint-Learning#1]
Hello trying to compile the GenerateTrainingSet I always get the error 

"C2719	'p': formal parameter with requested alignment of 16 won't be aligned GenerateTrainingSet 190"

**Comment by rspezialetti** [comment]
Which version of Visual Studio are you using?

**Comment by zgojcic** [comment]
I was using MS VS 2015 32bit with PCL 1.8.1 32 bit and OpenCV 3.2. 

Now I used 64 bit compiler with PCL 1.8.1. 64bit and OpenCV 3.3 and it works. Thanks for the quick response.

**Comment by rspezialetti** [comment]
Which version of Visual Studio are you using?
